export declare const colors: {
    '--primary-button-hover-shadow': string;
    '--primary-button-hover-inset-shadow': string;
    '--scrollbar-active-gray': string;
    '--scrollbar-inactive-gray': string;
    '--scrollbar-hover-gray': string;
    '--editor-text-pink': string;
    '--card-box-shadow': string;
    '--filter-red-icon': string;
    '--filter-green-icon': string;
    '--filter-purple-icon': string;
    '--filter-orange-icon': string;
    '--filter-white-icon': string;
    '--dark-blue-100': string;
    '--dark-blue-200': string;
    '--dark-blue-300': string;
    '--dark-blue-400': string;
    '--dark-blue-500': string;
    '--dark-blue-600': string;
    '--dark-blue-700': string;
    '--dark-blue-800': string;
    '--red-100': string;
    '--red-200': string;
    '--red-300': string;
    '--red-400': string;
    '--red-500': string;
    '--red-600': string;
    '--red-700': string;
    '--red-800': string;
    '--blue-100': string;
    '--blue-200': string;
    '--blue-300': string;
    '--blue-400': string;
    '--blue-500': string;
    '--blue-600': string;
    '--blue-700': string;
    '--blue-800': string;
    '--yellow-100': string;
    '--yellow-200': string;
    '--yellow-300': string;
    '--yellow-400': string;
    '--yellow-500': string;
    '--yellow-600': string;
    '--yellow-700': string;
    '--yellow-800': string;
    '--pink-100': string;
    '--pink-200': string;
    '--pink-300': string;
    '--pink-400': string;
    '--pink-500': string;
    '--pink-600': string;
    '--pink-700': string;
    '--pink-800': string;
    '--green-100': string;
    '--green-200': string;
    '--green-300': string;
    '--green-400': string;
    '--green-500': string;
    '--green-600': string;
    '--green-700': string;
    '--green-800': string;
    '--orange-100': string;
    '--orange-200': string;
    '--orange-300': string;
    '--orange-400': string;
    '--orange-500': string;
    '--orange-600': string;
    '--orange-700': string;
    '--orange-800': string;
    '--white': string;
    '--grey-100': string;
    '--grey-200': string;
    '--grey-300': string;
    '--grey-400': string;
    '--grey-500': string;
    '--grey-600': string;
    '--grey-700': string;
    '--grey-800': string;
    '--grey-900': string;
    '--black': string;
};
export interface Theme {
    light: Record<string, string>;
    dark: Record<string, string>;
}
declare const theme: {
    readonly light: {
        readonly '--text-primary': `rgb(${string})`;
        readonly '--text-secondary': `rgba(${string}, ${string})`;
        readonly '--text-tertiary': `rgba(${string}, ${string})`;
        readonly '--text-disabled': `rgba(${string}, ${string})`;
        readonly '--text-always-white': `rgb(${string})`;
        readonly '--text-always-black': `rgb(${string})`;
        readonly '--text-link': `rgb(${string})`;
        readonly '--text-destructive': `rgb(${string})`;
        readonly '--text-inverse': `rgb(${string})`;
        readonly '--icon-primary': `rgb(${string})`;
        readonly '--icon-secondary': `rgba(${string}, ${string})`;
        readonly '--icon-tertiary': `rgba(${string}, ${string})`;
        readonly '--icon-disabled': `rgba(${string}, ${string})`;
        readonly '--icon-always-white': `rgb(${string})`;
        readonly '--icon-always-black': `rgb(${string})`;
        readonly '--icon-link': `rgb(${string})`;
        readonly '--icon-destructive': `rgb(${string})`;
        readonly '--icon-inverse': `rgb(${string})`;
        readonly '--cta-primary-default': `rgb(${string})`;
        readonly '--cta-primary-hover': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--cta-primary-active': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--cta-primary-disabled': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-default': `rgb(${string})`;
        readonly '--cta-secondary-hover': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-active': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-disabled': "transparent";
        readonly '--cta-tertiary-default': "transparent";
        readonly '--cta-tertiary-hover': `rgba(${string}, ${string})`;
        readonly '--cta-tertiary-active': `rgba(${string}, ${string})`;
        readonly '--cta-tertiary-disabled': "transparent";
        readonly '--cta-destructive-default': "transparent";
        readonly '--cta-destructive-hover': `rgba(${string}, ${string})`;
        readonly '--cta-destructive-active': `rgba(${string}, ${string})`;
        readonly '--cta-chip-default': "transparent";
        readonly '--cta-chip-hover': `rgba(${string}, ${string})`;
        readonly '--cta-destructive-disabled': "transparent";
        readonly '--cta-navigation-default': "transparent";
        readonly '--cta-navigation-hover': `rgba(${string}, ${string})`;
        readonly '--cta-navigation-active': `rgba(${string}, ${string})`;
        readonly '--cta-navigation-disabled': "transparent";
        readonly '--border-primary': `rgba(${string}, ${string})`;
        readonly '--border-secondary': `rgba(${string}, ${string})`;
        readonly '--border-tertiary': `rgba(${string}, ${string})`;
        readonly '--border-hover': `rgba(${string}, ${string})`;
        readonly '--border-active': `rgb(${string})`;
        readonly '--border-destructive': `rgba(${string}, ${string})`;
        readonly '--bg-main-container': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-sidepanel': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l0-solid': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l0-glass': `rgba(245, 245, 245, ${string})`;
        readonly '--bg-l1-solid': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l1-glass': `rgba(${string}, ${string})`;
        readonly '--bg-l2-solid': `rgb(${string})`;
        readonly '--bg-l2-glass': `rgba(${string}, ${string})`;
        readonly '--bg-l3-solid': `rgb(${string})`;
        readonly '--bg-l3-glass': `rgba(${string}, ${string})`;
        readonly '--bg-emphasis': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-scrim': `rgba(${string}, ${string})`;
        readonly '--bg-cell-hover': `rgba(${string}, ${string})`;
        readonly '--bg-cell-active': `rgba(${string}, ${string})`;
        readonly '--bg-field-default': `rgba(${string}, ${string})`;
        readonly '--bg-field-hover': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-primary': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-secondary': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-tertiary': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-destructive': `rgba(${string}, ${string})`;
        readonly '--bg-code-gutter': "linear-gradient(90deg, #d8d8d8 1px, #f0f0f0 1px)";
        readonly '--accent-orange-primary': `rgb(${string})`;
        readonly '--accent-orange-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-green-primary': `rgb(${string})`;
        readonly '--accent-green-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-pink-primary': `rgb(${string})`;
        readonly '--accent-pink-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-yellow-primary': `rgb(${string})`;
        readonly '--accent-yellow-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-blue-primary': `rgb(${string})`;
        readonly '--accent-blue-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-red-primary': `rgb(${string})`;
        readonly '--accent-red-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-dark-blue-primary': `rgb(${string})`;
        readonly '--accent-dark-blue-secondary': `rgba(${string}, ${string})`;
        readonly '--editor-page-shadow': "60 64 67 / 15%) 0 1px 3px 1px";
        readonly '--tab-active-shadow': "0 123 255 / 25%";
        readonly '--shadow-l1': "0px 1px 3px rgba(0, 0, 0, 0.1), 0px 0px 2px rgba(0, 0, 0, 0.06)";
        readonly '--shadow-l2': "0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)";
        readonly '--shadow-l3': "0px 25px 50px -12px rgba(0, 0, 0, 0.25)";
        readonly '--inset-empty': "inset 1px 1px 0px rgba(0, 0, 0, 0.1)";
        readonly '--icon-bevel': "inset 0px -3px 0px 1px rgba(0, 0, 0, 0.1), inset 0px 1px 0px 1px rgba(255, 255, 255, 0.5)";
        readonly '--secondary-button-border': "inset 0px 1px 0px rgba(0, 0, 0, 0.1), inset 0px -1px 0px 1px rgba(0, 0, 0, 0.1)";
        readonly '--destructive-button-border': "inset 0px -1px 0px 1px rgba(215, 40, 40, 0.2), inset 0px 1px 0px rgba(215, 40, 40, 0.2)";
        readonly '--skiff-dropdown-shadow': "rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 2px 0 inset";
        readonly '--skiff-font-size-shadow': "rgba(225, 228, 232, 0.2) 0 2px 0 inset";
        readonly '--skiff-drawer-shadow': "0px 0px 40px rgba(0, 0, 0, 0.1)";
        readonly '--filter-dark-card-bg': "none";
        readonly '--filter-dark-lock-icon': "none";
        readonly '--filter-dark-icon': "none";
        readonly '--filter-white-icon-dark': "none";
        readonly '--skiff-table-menu-input': "#1b27334d";
        readonly '--skiff-header-hover': "rgba(55, 53, 47, 0.12)";
        readonly '--skiff-header-active': "rgba(55, 53, 47, 0.16)";
        readonly '--skiff-code-mark-color': `rgb(${string})`;
        readonly '--skiff-code-mark-bg': `rgba(${string}, ${string})`;
        readonly '--bg-cell-unread': `rgb(${string})`;
        readonly '--status-bar-color': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--primary-button-hover-shadow': string;
        readonly '--primary-button-hover-inset-shadow': string;
        readonly '--scrollbar-active-gray': string;
        readonly '--scrollbar-inactive-gray': string;
        readonly '--scrollbar-hover-gray': string;
        readonly '--editor-text-pink': string;
        readonly '--card-box-shadow': string;
        readonly '--filter-red-icon': string;
        readonly '--filter-green-icon': string;
        readonly '--filter-purple-icon': string;
        readonly '--filter-orange-icon': string;
        readonly '--filter-white-icon': string;
        readonly '--dark-blue-100': string;
        readonly '--dark-blue-200': string;
        readonly '--dark-blue-300': string;
        readonly '--dark-blue-400': string;
        readonly '--dark-blue-500': string;
        readonly '--dark-blue-600': string;
        readonly '--dark-blue-700': string;
        readonly '--dark-blue-800': string;
        readonly '--red-100': string;
        readonly '--red-200': string;
        readonly '--red-300': string;
        readonly '--red-400': string;
        readonly '--red-500': string;
        readonly '--red-600': string;
        readonly '--red-700': string;
        readonly '--red-800': string;
        readonly '--blue-100': string;
        readonly '--blue-200': string;
        readonly '--blue-300': string;
        readonly '--blue-400': string;
        readonly '--blue-500': string;
        readonly '--blue-600': string;
        readonly '--blue-700': string;
        readonly '--blue-800': string;
        readonly '--yellow-100': string;
        readonly '--yellow-200': string;
        readonly '--yellow-300': string;
        readonly '--yellow-400': string;
        readonly '--yellow-500': string;
        readonly '--yellow-600': string;
        readonly '--yellow-700': string;
        readonly '--yellow-800': string;
        readonly '--pink-100': string;
        readonly '--pink-200': string;
        readonly '--pink-300': string;
        readonly '--pink-400': string;
        readonly '--pink-500': string;
        readonly '--pink-600': string;
        readonly '--pink-700': string;
        readonly '--pink-800': string;
        readonly '--green-100': string;
        readonly '--green-200': string;
        readonly '--green-300': string;
        readonly '--green-400': string;
        readonly '--green-500': string;
        readonly '--green-600': string;
        readonly '--green-700': string;
        readonly '--green-800': string;
        readonly '--orange-100': string;
        readonly '--orange-200': string;
        readonly '--orange-300': string;
        readonly '--orange-400': string;
        readonly '--orange-500': string;
        readonly '--orange-600': string;
        readonly '--orange-700': string;
        readonly '--orange-800': string;
        readonly '--white': string;
        readonly '--grey-100': string;
        readonly '--grey-200': string;
        readonly '--grey-300': string;
        readonly '--grey-400': string;
        readonly '--grey-500': string;
        readonly '--grey-600': string;
        readonly '--grey-700': string;
        readonly '--grey-800': string;
        readonly '--grey-900': string;
        readonly '--black': string;
    };
    readonly dark: {
        readonly '--text-primary': `rgb(${string})`;
        readonly '--text-secondary': `rgba(${string}, ${string})`;
        readonly '--text-tertiary': `rgba(${string}, ${string})`;
        readonly '--text-disabled': `rgba(${string}, ${string})`;
        readonly '--text-always-white': `rgb(${string})`;
        readonly '--text-always-black': `rgb(${string})`;
        readonly '--text-link': `rgb(${string})`;
        readonly '--text-destructive': `rgb(${string})`;
        readonly '--text-inverse': `rgb(${string})`;
        readonly '--icon-primary': `rgb(${string})`;
        readonly '--icon-secondary': `rgba(${string}, ${string})`;
        readonly '--icon-tertiary': `rgba(${string}, ${string})`;
        readonly '--icon-disabled': `rgba(${string}, ${string})`;
        readonly '--icon-always-white': `rgb(${string})`;
        readonly '--icon-always-black': `rgb(${string})`;
        readonly '--icon-link': `rgb(${string})`;
        readonly '--icon-destructive': `rgb(${string})`;
        readonly '--icon-inverse': `rgb(${string})`;
        readonly '--cta-primary-default': `rgb(${string})`;
        readonly '--cta-primary-hover': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--cta-primary-active': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--cta-primary-disabled': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-default': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-hover': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-active': `rgba(${string}, ${string})`;
        readonly '--cta-secondary-disabled': "transparent";
        readonly '--cta-tertiary-default': "transparent";
        readonly '--cta-tertiary-hover': `rgba(${string}, ${string})`;
        readonly '--cta-tertiary-active': `rgba(${string}, ${string})`;
        readonly '--cta-tertiary-disabled': "transparent";
        readonly '--cta-destructive-default': `rgba(${string}, ${string})`;
        readonly '--cta-destructive-hover': `rgba(${string}, ${string})`;
        readonly '--cta-destructive-active': `rgba(${string}, ${string})`;
        readonly '--cta-destructive-disabled': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--cta-chip-default': "transparent";
        readonly '--cta-chip-hover': `rgba(${string}, ${string})`;
        readonly '--cta-navigation-default': "transparent";
        readonly '--cta-navigation-hover': `rgba(${string}, ${string})`;
        readonly '--cta-navigation-active': `rgba(${string}, ${string})`;
        readonly '--cta-navigation-disabled': "transparent";
        readonly '--border-primary': `rgba(${string}, ${string})`;
        readonly '--border-secondary': `rgba(${string}, ${string})`;
        readonly '--border-tertiary': `rgba(${string}, ${string})`;
        readonly '--border-hover': `rgba(${string}, ${string})`;
        readonly '--border-active': `rgb(${string})`;
        readonly '--border-destructive': `rgba(${string},${string})`;
        readonly '--bg-main-container': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-sidepanel': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l0-solid': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l0-glass': `rgba(10, 10, 10, ${string})`;
        readonly '--bg-l1-solid': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l1-glass': `rgba(20, 20, 20, ${string})`;
        readonly '--bg-l2-solid': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l2-glass': `rgba(31, 31, 31, ${string})`;
        readonly '--bg-l3-solid': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--bg-l3-glass': `rgba(41, 41, 41, ${string})`;
        readonly '--bg-emphasis': `rgb(${string})`;
        readonly '--bg-scrim': `rgba(${string}, ${string})`;
        readonly '--bg-cell-hover': `rgba(${string}, ${string})`;
        readonly '--bg-cell-active': `rgba(${string}, ${string})`;
        readonly '--bg-field-default': `rgba(${string}, ${string})`;
        readonly '--bg-field-hover': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-primary': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-secondary': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-tertiary': `rgba(${string}, ${string})`;
        readonly '--bg-overlay-destructive': `rgba(${string}, ${string})`;
        readonly '--bg-code-gutter': "linear-gradient(0deg,rgba(0, 0, 0, 0) 1px, #282828 1px)";
        readonly '--accent-orange-primary': `rgba(${string}, ${string})`;
        readonly '--accent-orange-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-green-primary': `rgba(${string}, ${string})`;
        readonly '--accent-green-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-pink-primary': `rgba(${string}, ${string})`;
        readonly '--accent-pink-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-yellow-primary': `rgba(${string}, ${string})`;
        readonly '--accent-yellow-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-blue-primary': `rgba(${string}, ${string})`;
        readonly '--accent-blue-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-red-primary': `rgba(${string}, ${string})`;
        readonly '--accent-red-secondary': `rgba(${string}, ${string})`;
        readonly '--accent-dark-blue-primary': `rgba(${string}, ${string})`;
        readonly '--accent-dark-blue-secondary': `rgba(${string}, ${string})`;
        readonly '--editor-page-shadow': "60 64 67 / 15%) 0 1px 3px 1px";
        readonly '--tab-active-shadow': "0 123 255 / 25%";
        readonly '--shadow-l1': "0px 1px 3px rgba(0, 0, 0, 0.3), 0px 1px 2px rgba(0, 0, 0, 0.26)";
        readonly '--shadow-l2': "0px 10px 15px -3px rgba(0, 0, 0, 0.3), 0px 4px 6px -2px rgba(0, 0, 0, 0.25)";
        readonly '--shadow-l3': "0px 25px 50px -12px rgba(0, 0, 0, 0.55)";
        readonly '--inset-empty': "inset 0px -1px 0px rgba(255, 255, 255, 0.1)";
        readonly '--icon-bevel': "inset 0px -3px 0px 1px rgba(0, 0, 0, 0.1), inset 0px 1px 0px 1px rgba(255, 255, 255, 0.5)";
        readonly '--secondary-button-border': "inset 0px 1px 0px rgb(255 255 255 / 20%), inset 0px -1px 0px 1px hsl(0deg 0% 100% / 20%)";
        readonly '--destructive-button-border': "inset 0px -1px 0px 1px rgba(255, 143, 143, 0.12), inset 0px 1px 0px rgba(255, 143, 143, 0.12)";
        readonly '--skiff-dropdown-shadow': "rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 2px 0 inset";
        readonly '--skiff-font-size-shadow': "rgba(225, 228, 232, 0.2) 0 2px 0 inset";
        readonly '--skiff-drawer-shadow': "0px 0px 40px rgba(0, 0, 0, 0.1)";
        readonly '--filter-dark-card-bg': "none";
        readonly '--filter-dark-icon': "none";
        readonly '--filter-white-icon-dark': "none";
        readonly '--skiff-table-menu-input': "#1b27334d";
        readonly '--skiff-header-hover': "rgba(55, 53, 47, 0.12)";
        readonly '--skiff-header-active': "rgba(55, 53, 47, 0.16)";
        readonly '--skiff-code-mark-color': `rgb(${string})`;
        readonly '--skiff-code-mark-bg': `rgba(${string}, ${string})`;
        readonly '--bg-cell-unread': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--status-bar-color': `linear-gradient(0deg, rgba(${string}, ${string}), rgba(${string}, ${string})), rgb(${string})`;
        readonly '--primary-button-hover-shadow': string;
        readonly '--primary-button-hover-inset-shadow': string;
        readonly '--scrollbar-active-gray': string;
        readonly '--scrollbar-inactive-gray': string;
        readonly '--scrollbar-hover-gray': string;
        readonly '--editor-text-pink': string;
        readonly '--card-box-shadow': string;
        readonly '--filter-red-icon': string;
        readonly '--filter-green-icon': string;
        readonly '--filter-purple-icon': string;
        readonly '--filter-orange-icon': string;
        readonly '--filter-white-icon': string;
        readonly '--dark-blue-100': string;
        readonly '--dark-blue-200': string;
        readonly '--dark-blue-300': string;
        readonly '--dark-blue-400': string;
        readonly '--dark-blue-500': string;
        readonly '--dark-blue-600': string;
        readonly '--dark-blue-700': string;
        readonly '--dark-blue-800': string;
        readonly '--red-100': string;
        readonly '--red-200': string;
        readonly '--red-300': string;
        readonly '--red-400': string;
        readonly '--red-500': string;
        readonly '--red-600': string;
        readonly '--red-700': string;
        readonly '--red-800': string;
        readonly '--blue-100': string;
        readonly '--blue-200': string;
        readonly '--blue-300': string;
        readonly '--blue-400': string;
        readonly '--blue-500': string;
        readonly '--blue-600': string;
        readonly '--blue-700': string;
        readonly '--blue-800': string;
        readonly '--yellow-100': string;
        readonly '--yellow-200': string;
        readonly '--yellow-300': string;
        readonly '--yellow-400': string;
        readonly '--yellow-500': string;
        readonly '--yellow-600': string;
        readonly '--yellow-700': string;
        readonly '--yellow-800': string;
        readonly '--pink-100': string;
        readonly '--pink-200': string;
        readonly '--pink-300': string;
        readonly '--pink-400': string;
        readonly '--pink-500': string;
        readonly '--pink-600': string;
        readonly '--pink-700': string;
        readonly '--pink-800': string;
        readonly '--green-100': string;
        readonly '--green-200': string;
        readonly '--green-300': string;
        readonly '--green-400': string;
        readonly '--green-500': string;
        readonly '--green-600': string;
        readonly '--green-700': string;
        readonly '--green-800': string;
        readonly '--orange-100': string;
        readonly '--orange-200': string;
        readonly '--orange-300': string;
        readonly '--orange-400': string;
        readonly '--orange-500': string;
        readonly '--orange-600': string;
        readonly '--orange-700': string;
        readonly '--orange-800': string;
        readonly '--white': string;
        readonly '--grey-100': string;
        readonly '--grey-200': string;
        readonly '--grey-300': string;
        readonly '--grey-400': string;
        readonly '--grey-500': string;
        readonly '--grey-600': string;
        readonly '--grey-700': string;
        readonly '--grey-800': string;
        readonly '--grey-900': string;
        readonly '--black': string;
    };
};
export declare const themeNames: Theme & typeof theme;
export {};
//# sourceMappingURL=theme.d.ts.map